// Get Polylux from the official package repository
#import "@preview/polylux:0.4.0": *
#import "@preview/ctheorems:1.1.3": *

#show: thmrules.with(qed-symbol: $square$)

#set page(margin: 1.5cm, numbering: "1 of 1")
#let theorem = thmbox("theorem", "Theorem", fill: rgb("#eeffee"))
#let proposition = thmplain("proposition", "Proposition")
#let corollary = thmplain(
  "corollary",
  "Corollary",
  base: "theorem",
  titlefmt: strong
)
#let definition = thmbox("definition", "Definition", inset: (x: 1em))

#let example = thmplain("example", "Example").with(numbering: none)
#let exercise = thmplain("exercise", "Exercise").with(numbering: none)
#let proof = thmproof("proof", "Proof")

// Make the paper dimensions fit for a presentation and the text larger
#set page(paper: "presentation-16-9")
#set text(size: 16pt, font: "Comic Sans MS")

#slide[
  #set align(horizon)
  = Subgroups, Lagrange's Theorem and its applications

  Tim Hsiung

  January 25, 2026
]

#slide[
  == Outline

  - Subgroups
  - How to construct subgroups
  - Cyclic groups and order of elements
  - Lagrange's Theorem
  - Use Lagrange's theorem to prove Fermat's Little Theorem

  This slide will cover some of Dummit Foote Chapter 2, and section 3.2.
]

#slide[
  == Basic definitions and properties of subgroups

  #definition("Subgroups")[
    A subset $H$ of $G$ is a subgroup of $G$ if it is itself a group under the operation of $G$.

    More precisely,
    - $H$ is non-empty.
    - (Closed under the binary operation) For all $a, b in H$, we have $a b in H$.
    - (Closed under the inversion) For all $a in H$, we have $a^(-1) in H$.
  ]

  #example[
    The trivial subgroup ${e}$ is a subgroup of any group $G$.
  ]
  #example[
    Any group $G$ is a subgroup of itself.
  ]
  #example("Center")[
    The center $Z(G) := {g in G | g x = x g "for all" x in G}$ of a group $G$ is a subgroup of $G$.
  ]
]
#slide[
  #theorem("The subgroup criterion")[
    Let $G$ be a group and $H subset.eq G$, then $H$ is a subgroup of $G$ if and only if

    - $H$ is non-empty.
    - $a b^(-1) in H$ for all $a, b in H$.
  ]

  #proof[
    The $(arrow.r.double)$ direction is trivial.

    For the $(arrow.l.double)$ direction, we need to verify that $H$ is closed under the inversion.

    Let $a in H$. Then $e = a a^(-1) in H$ by the assumption. Therefore, $a^(-1) = e a^(-1) in H$ by the closure of $H$ under the binary operation.

    Therefore, $H$ is a subgroup of $G$.
  ]
]
#slide[
  #theorem[
    Furthermore, if $H$ is finite, then it is sufficient to check that $H$ is non-empty and closed under the binary operation.
  ]
  #proof[
    Let $a in H$. We now verify that $a^(-1) in H$.

    Consider the set ${a^n | n in NN} subset.eq H$.

    Hint: this is a finite set.
  ]
]
#slide[
  #theorem[
    Let ${H_alpha}_(alpha in A)$ be a collection of subgroups of $G$. Then $ inter.big_(alpha in A) H_alpha $ is a subgroup of $G$.
  ]
  #proof[
    Use the subgroup criterion.
  ]

  The above theorem shows that the intersection of subgroups is also a subgroup.
]
#slide[
  How about the union of subgroups? How about the product of subgroups?

  #exercise[
    Show that $H union K <= G$ if and only if $H subset.eq K$ or $K subset.eq H$.
  ]
  #exercise[
    Let $H K := {h k | h in H, k in K}$. Show that $H K <= G$ if and only if $H K = K H$.
  ]
]
#slide[
  == Generated subgroups

  #definition("Subgroup generated by a subset")[
    Let $S subset.eq G$. The subgroup "generated" by $S$ is the smallest subgroup of $G$ that contains $S$. We denote it by $chevron.l S chevron.r$.

    More precisely, $ chevron.l S chevron.r := inter.big_(H <= G, S subset.eq H) H $
  ]

  This is similar to the concept of "span" in linear algebra.
]
#slide[
  #theorem("Another definition of the subgroup generated by a subset")[

    Let $S subset.eq G$. Then $chevron.l S chevron.r$ is the set of all finite products of elements of $S$ and their inverses. More precisely, let $overline(S) = {s_1 s_2 ... s_n | n in NN, s_i in S "or" s_i in S^(-1)}$, then $chevron.l S chevron.r = overline(S)$.
  ]
  If you are still familiar with linear algebra, recall that the span of a set of vectors is also the set of all linear combinations of the vectors in the set. The concepts are similar.
  #proof[
    First, use the subgroup criterion to show that $overline(S) <= G$.

    Then verify that $chevron.l S chevron.r = overline(S)$:

    - $chevron.l S chevron.r <= overline(S)$: because $overline(S)$ is a subgroup containing $S$.
    - $overline(S) <= chevron.l S chevron.r$: observe that each element of $overline(S)$ is a finite product of elements of $S$ and their inverses.
  ]
]

#slide[
  #exercise[
    Find the generated subgroup of the following sets:
    - $S = {3}$ in $ZZ$
    - $S = {r}$ in $D_8$
    - $S = {r^2}$ in $D_8$
    - $S = {s}$ in $D_8$
    - $S = {s r}$ in $D_8$
    - $S = {s, r^2}$ in $D_8$
    - $S = {j} in Q_8$
    - $S = {-1} in Q_8$
  ]
]

#slide[
  #definition("Cyclic groups")[
    A group $G$ is cyclic if there exists $g in G$ such that $G = chevron.l g chevron.r$. The element $g$ is called a generator of $G$.
  ]
  #definition("Cyclic subgroups")[
    A subgroup $H$ of $G$ is cyclic if there exists $g in G$ such that $H = chevron.l g chevron.r$.
  ]

  #example[
    $ZZ = chevron.l 1 chevron.r$ is cyclic.
    The subgroup $chevron.l r chevron.r$ of $D_8$ is cyclic.
    The subgroup $chevron.l j chevron.r$ of $Q_8$ is cyclic.
  ]
  #exercise[
    Is $QQ$ cyclic? Why or why not?
  ]
]

#slide[
  == Order of elements and groups

  #definition("Order of an element")[
    The order of an element $g in G$ is the smallest positive integer $n$ such that $g^n = e$. We denote it by $|g|$. If no such $n$ exists, we say that $g$ has infinite order or $|g| = infinity$.
  ]
  #exercise[
    Find the order of the elements in the following groups:
    - $1 in ZZ$
    - $r, r^2, r^3, s, s r in D_8$
  ]
  #exercise[
    Let $g in G$. Show that $|g| = |g^(-1)|$.
  ]
  #exercise[
    Let $G$ be a group such that $|g| = 2$ for all $g in G$. Show that $G$ is abelian.
  ]
  #exercise[
    Let $G := {z in CC | z^n = 1 "for some" n in NN} subset.eq CC^times$. Show that $G$ is a group under multiplication. Show that every element of $G$ has finite order, but $G$ is infinite.
  ]
]

#slide[
  #definition("Order of a group")[
    The order of a group $G$ is the number of elements in $G$. We denote it by $|G|$.
  ]
  #theorem[
    Let $g in G$. Then $|g| = |chevron.l g chevron.r|$.
  ]
  #exercise[Find the order of the generated subgroups in the previous exercise.]
]

#slide[
  == Lagrange's Theorem

  #theorem("Lagrange's Theorem")[
    Let $G$ be finite and $H <= G$. Then $|H|$ divides $|G|$.
  ]

  Lagrange's Theorem is a very important theorem in group theory. It tells us that the order of a subgroup divides the order of the group.

  #exercise[Verify Lagrange's Theorem with the groups $D_8, Q_8$.]
  #exercise[Let $G$ be a group of prime order, then the only subgroups of $G$ are ${e}$ and $G$ itself. Furthermore, $G$ must be cyclic.]

  To prove this theorem, we will need the concept of *cosets*.
]

#slide[
  == Cosets

  #definition("Cosets")[
    Let $H <= G$, then we denote $G slash H$ "the set of (left) cosets"

    $ G slash H := { g H | g in G } $

    where $g H := {g h | h in H}$.
  ]
  #exercise[
    Find the cosets of the subgroups $chevron.l r chevron.r, chevron.l s chevron.r$ in $D_8$.
  ]
  Note: cosets are generally not subgroups!
  #theorem[
    Let $H <= G$ and $a, b in G$. Then either $a H = b H$ or $a H inter b H = emptyset$.
  ]
  #proof[
    Suppose $a H inter b H != emptyset$. Then there exists $h_1, h_2 in H$ such that $a h_1 = b h_2$.
    Then $a = b h_2 h_1^(-1)$. Therefore, $a H = (b h_2 h_1^(-1)) H = b H$.
  ]
]
#slide[
  #theorem[
    All the cosets of $H$ in $G$ have the same size.
  ]
  #proof[
    Let $a in G$ and consider the map $phi_a: H -> a H$ defined by $phi_a (h) = a h$. This map is bijective (you can verify 1-1 by cancellation law). Therefore, the size of $H$ is the same as the size of $a H$. Use this to show that all the cosets of $H$ in $G$ have the same size.
  ]
  #definition("Index of a subgroup")[
    The index of a subgroup $H$ in $G$ (not necessarily finite) is the number of cosets of $H$ in $G$. We denote it by $[G : H]$.
  ]
  #corollary[
    - $G slash H$ forms a partition of $G$.
    - (Lagrange's Theorem) $|G slash H| = (|G|) / (|H|) = [G : H]$.
  ]
]
#slide[
  #exercise[
    Let $H <= G$. Find the index of $H$ in $G$ for the following groups:

    + $H = 5ZZ, G = ZZ$
    + $H = ZZ, G = RR$
    + $H = 5ZZ, G = RR$
    + $H = ZZ, G = QQ$
    + $H = QQ, G = RR$
  ]
]
#slide[
  == Fermat's Little Theorem

  We know that Fermat's Little Theorem is important in cryptography. We will now prove it using Lagrange's Theorem.
  #theorem[
    Let $p$ be a prime and $a in ZZ$. Then $a^(p - 1) equiv 1 (mod p)$.
  ]
  You probably already know how to prove this theorem by letting $a = b + 1$ and then using the binomial theorem. We will now prove it using Lagrange's Theorem.

  #theorem[
    Let $a in G$. Then $|a| | |G|$.
  ]
  #corollary[
    Let $a in G$. Then $a^(|G|) = e$.
  ]
  #proof("of Fermat's Little Theorem")[
    Consider the group $(ZZ slash p ZZ)^times := {1, ..., p - 1}$. The group operation is multiplication modulo $p$. The order of this group is $p - 1$.
  ]
]
#slide[
  #exercise[
    Recall that $phi(n)$ is the Euler's totient function, which is the number of integers less than $n$ that are coprime to $n$.

    Consider the group $(ZZ slash n ZZ)^times := {a = 1, ..., n - 1 | gcd(a, n) = 1}$.
    Show that $|(ZZ slash n ZZ)^times| = phi(n)$. Deduce that $m^(phi(n)) equiv 1 (mod n)$ for all $m$ coprime to $n$.
  ]
]